#!/bin/sh

FIFO="/tmp/dvtm-status.$$"
RND=$(openssl rand -hex 8)

[ -p "$FIFO" ] || mkfifo -m 600 "$FIFO" || exit 1

while true; do
	echo "$RND  $(date +"%F %T %s") $HOSTNAME "
	[ $(( $(date +%s) % 60 )) -eq 0 ] && RND=$(openssl rand -hex 8) #if time is divisible by 60 set new RND
	sleep 1s
done > "$FIFO" &

STATUS_PID=$!
dvtm -s "$FIFO" "$@" 2> /dev/null
kill $STATUS_PID
wait $STATUS_PID 2> /dev/null
rm -f "$FIFO"
